apiVersion: v1
kind: PersistentVolume
metadata:
  name: message-mysql
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: message-mysql
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs-share/message-mysql/data
    server: 10.141.212.138