apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: redis
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs-share/redis/data
    server: 10.141.212.138