apiVersion: v1
kind: PersistentVolume
metadata:
  name: ui-service-conf
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs-share/ui-service/nginx.conf
    server: 10.141.212.138