version: '3'
services:
#  # redis
#  redis:
#    image: redis
#    ports:
#    - 6379:6379
#    restart: always
#    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
#    volumes:
#    - ./redis/redis.cnf:/etc/redis/redis.conf
#    - ./redis/data:/etc/redis/data
#    networks:
#      - withme-network

  withme-mysql:
    image: mysql:5.6
    ports:
      - 3307:3306
    command: [
      --character-set-server=utf8mb4,
      --collation-server=utf8mb4_unicode_ci
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: withme
    volumes:
      - ./withme-mysql/mysql.cnf:/etc/my.cnf
      - ./withme-mysql/data:/var/lib/mysql
    networks:
      - withme-network

  # service
  user-service:
    build: user-service
    image: withme3.0/user-service
    restart: always
    depends_on:
      - withme-mysql
    ports:
    - 21003:8081
    networks:
    - withme-network

  user-relation-service:
    build: user-relation-service
    image: withme3.0/user-relation-service
    depends_on:
      - withme-mysql
    restart: always
    ports:
    - 21004:8081
    networks:
    - withme-network

  message-service:
    build: message-service
    image: withme3.0/message-service
    depends_on:
    - withme-mysql
    restart: always
    ports:
    - 21005:8081
    networks:
    - withme-network

  group-service:
      build: group-service
      image: withme3.0/group-service
      depends_on:
      - withme-mysql
      restart: always
      ports:
      - 21006:8081
      networks:
      - withme-network

  group-message-service:
      build: group-message-service
      image: withme3.0/group-message-service
      depends_on:
      - withme-mysql
      restart: always
      ports:
      - 21007:8081
      networks:
      - withme-network

  offline-message-service:
      build: offline-message-service
      image: withme3.0/offline-message-service
      depends_on:
      - withme-mysql
      restart: always
      ports:
      - 21008:8081
      networks:
      - withme-network

  # ui-service
  ui-service:
    build: ui-service
    image: withme3.0/ui-service
    restart: always
    ports:
      - 80:8081
    networks:
      - withme-network

  # websocket service
  websocket-server-service:
    build: websocket-server-service
    image: withme3.0/websocket-server-service
    restart: always
    ports:
    - 21002:8282
    networks:
    - withme-network


networks:
  withme-network:
    driver: bridge