version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - 7777:8080
      - 7778:50000
    volumes:
      - /var/jenkins_home:/var/jenkins_home

networks:
  withme-network:
    driver: bridge