#apiVersion: extensions/v1beta1
#kind: Deployment
#metadata:
#  annotations:
#    kompose.cmd: kompose convert -f docker-compose.yml
#    kompose.version: 1.18.0 (06a2e56)
#  creationTimestamp: null
#  labels:
#    io.kompose.service: redis
#  name: redis
#spec:
#  replicas: 1
#  strategy:
#    type: Recreate
#  template:
#    metadata:
#      creationTimestamp: null
#      labels:
#        io.kompose.service: redis
#    spec:
#      containers:
#      - args:
#        - /bin/bash
#        - -c
#        - redis-server /etc/redis/redis.conf
#        image: redis
#        name: redis
#        ports:
#        - containerPort: 6379
#        resources: {}
#        volumeMounts:
#        - mountPath: /etc/redis/data
#          name: redis-claim0
#      restartPolicy: Always
#      volumes:
#      - name: redis-claim0
#        persistentVolumeClaim:
#          claimName: redis-claim0
#status: {}
