apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: user-relation-service
  name: user-relation-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: user-relation-service
    spec:
      containers:
      - image: icedsoul/user-relation-service
        name: user-relation-service
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
